// {
//     "kind": "identitytoolkit#VerifyPasswordResponse",
//     "localId": "JhfxaYIaSjcCdANWzvvSFuyaxnU2",
//     "email": "test@gmail.com",
//     "displayName": "",
//     "idToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImM2MGI5ZGUwODBmZmFmYmZjMTgzMzllY2Q0NGFjNzdmN2ZhNGU4ZDMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYW5ndWxhci05YjVkMiIsImF1ZCI6ImFuZ3VsYXItOWI1ZDIiLCJhdXRoX3RpbWUiOjE2OTMzNzMzNjUsInVzZXJfaWQiOiJKaGZ4YVlJYVNqY0NkQU5XenZ2U0Z1eWF4blUyIiwic3ViIjoiSmhmeGFZSWFTamNDZEFOV3p2dlNGdXlheG5VMiIsImlhdCI6MTY5MzM3MzM2NSwiZXhwIjoxNjkzMzc2OTY1LCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.Zq337YNhis3f8pcR5qllKJt-UzkCzssIAV3AdAyDAJJSA31fAD6fozD-R9V2s2vSmvHmss67abHWrKL-NQ0FUZZPtZ6Vc-6oUFkYJEsEhimjqcpDIy8hUlWSjqQiVrGJFNIr2kKSNryk3czzG2R3kinrkqBs_pxAmsUf1RLMKNQaKlJbm92nucMuoNZSog5N_r_IIPRnxdVlu2Q8Yzocg4-Fvg__JjNy6p5YwGG63mI_2K3IuvsqIV6efHAHcWujuOpHb7Q9k1RHrsQfoV7KNfN0LU0IKpA3Cl-vj5_RhTXVvJxNEYy2DBsOxiSR1Oy_74PaR2Npd4boG7kWgrU5lQ",
//     "registered": true,
//     "refreshToken": "AMf-vBz4oq5lAVMPZ7Z0W9sjV1R-zshmmFkjV4QGDpsTrRyOmWFyUnzBxAWT6DhoVRdH0wpBOw0S4b05ibsU_XgAFFbW57fBmxeY3pEDNg_hNidibuea5snv1SvKnZx1bvmGGZfGiTogxPFSxG_OGcjG47OA3dcTVxih2z0qiFx5DPUkZxwAMLQTarAPWfLzOUr0HhlX2227",
//     "expiresIn": "3600"
// }// Generated by https://quicktype.io

// export interface TopLevel {
//     kind:         string;
//     localId:      string;
//     email:        string;
//     displayName:  string;
//     idToken:      string;
//     registered:   boolean;
//     refreshToken: string;
//     expiresIn:    string;
// }
